# Site Settings
baseurl: ""
url : "https://johnzon3.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : John Kim
    description : 재미있게 살고싶은 개발자
    experience :
      - start : 2013-06-15
        end : 2015-09-01
        experience : LINE corp, Security Dept, Application Security Team
      - start : 2015-09-01
        end : 2021-12-06
        experience : LINE corp, Data Platform Dept, 
      - start : 2021-12-06
        end : Current
        experience : LINEPLUS corp, Message Data Engineering Center, DP Part
    skills : 
      - skill : Programming languages - Java/Python/Scala
        value : 70  # Percent value
      - skill : Hadoop ecosystems - HDFS/YARN/Hive/Presto/Spark/HBase
        value : 70  # Percent value
      - skill : Development environments - IntelliJ/Eclipse/Github/Jenkins
        value : 70  # Percent value
      - skill : Web Application - Spring Boot/Flask
        value : 60  # Percent value
      - skill : Data collection tools - Flink/Fluentd/Filebeat/Logstash/Elasticsearch
        value : 50  # Percent value
      - skill : Operating/monitoring tools - Kubernetes/Ansible/Grafana/Prometheus +
        value : 50  # Percent value
      
        
  # Icons
  icons :
    email: johnzon3@gmail.com
    linkedin: https://www.linkedin.com/in/johnzone/
    github: johnzon3
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
